### ISSUE TITLE
Error: failed to get version on LS start with NeoVim & coc.nvim

### ISSUE THREAD

**Issue by grem11n** [hashicorp/terraform-ls#52]
### Server Version
```
❯ terraform-ls -v
0.1.0
```

### Terraform Version
```
❯ terraform version
Terraform v0.11.14
```

Terraform is installed using `tfenv`
```
❯ tfenv -v
tfenv 1.0.1
```

### Client Version
```
❯ nvim --version
NVIM v0.5.0-nightly-97-g71ee46acc
```
`coc.nvim` from the recent `master`:
```
❯ git rev-parse HEAD
b1e526345ca1ba0986a191f2fc38e606378414c5
❯ git status
On branch master
```

### Log Output
```
[coc.nvim] Server languageserver.terraform failed to start: failed to get version: terraform (pid 76092) exited (code 1): exit status 1
[coc.nvim] Server languageserver.terraform failed to start: failed to get version: terraform (pid 76876) exited (code 1): exit status 1
stdout: ""
stderr: "/usr/local/Cellar/tfenv/1.0.1/bin/terraform: line 6: /Users/yuriirochniak/Repo/terraform/tfenv: No such file or directory\n"
```

### Expected Behavior
Language server starts

### Actual Behavior
Language server fails to start with the error above

### Steps to Reproduce
1. You need to have NeoVim and coc.nvim installed
2. Install `terraform-ls` as described in README
3. LS configuration for coc:
```
{
    "languageserver": {
         "terraform": {
              "command": "terraform-ls",
              "args": ["serve"],
              "trace.server": "verbose",
              "filetypes": [
                  "terraform",
                  "tf"
              ],
              "initializationOptions": {},
              "settings": {}
          }
    }
}
```
4. Open any `.tf` file

**Comment by radeksimko** [comment]
Hi @grem11n 
Thank you for the report. I haven't had chance to try the LS out in NeoVim yet, nor try LS in combination with tfenv, but we do intend to support this combination and in theory it _should_ just work.

In other words the error is certainly weird and not expected.

That said the LS is designed to work with Terraform versions `>= 0.12` due to 0.12 introducing machine-readable schemas, so once we fix the bug I'd just expect NeoVim in your particular case to return a variation of this error:

https://github.com/hashicorp/terraform-ls/blob/362bd3e24054734428618d56c7cf90b20498f328/langserver/handlers/initialize.go#L71-L73

**Comment by radeksimko** [comment]
I managed to reproduce this with tfenv `1.0.1`, but also managed to fix it by upgrading to `1.0.2`, I suspect this may be relevant patch which made it work:
https://github.com/tfutils/tfenv/commit/c3f5d5e2626d76e0d153616e3976c4012e6a6137

@grem11n Can you try upgrading tfenv?

I'm not sure how NeoVim surfaces errors from LS requests, but you should at least see the following in the log:
```
2020/04/17 18:34:24 exec.go:114: Running /usr/local/bin/terraform ["version"] in "/private/var/workspace/tf-test/github"...
2020/04/17 18:34:25 exec.go:140: terraform run (/usr/local/bin/terraform ["version"], in "/private/var/workspace/tf-test/github", pid 3278) finished with exit code 0
2020/04/17 18:34:25 initialize.go:65: Unsupported terraform version: terraform version 0.11.14 is not supported in schema storage (supported: >= 0.12.0)
2020/04/17 18:34:25 rpc_logger.go:45: Error for "initialize" (ID 1): [-32098] terraform version 0.11.14 is not supported (supported: >= 0.12.0). Please upgrade or make supported version available in $PATH and reopen /private/var/workspace/tf-test/github
```

**Comment by radeksimko** [comment]
@grem11n I understand you may be busy with other things, but to make sure we can focus on active issues I'm going to close this one by the end of this week if I receive no further response with the assumption that this can be solved by upgrading `tfenv`.

btw. I added a NeoVim usage guide: https://github.com/hashicorp/terraform-ls/pull/54
